### ISSUE TITLE
Compile error using Deno 1.11

### ISSUE THREAD

**Issue by prathithacb** [oscarotero/keep-a-changelog#20]
Thanks for this great library, we were trying to use it with Deno 1.11 and saw the following error:

```bash
Check https://raw.githubusercontent.com/oscarotero/keep-a-changelog/deno/bin.js
error: TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    if (high!.operator === comp || high!.operator === ecomp) {
              ~~~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1744:15

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    if (high!.operator === comp || high!.operator === ecomp) {
                                         ~~~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1744:42

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
      (!low!.operator || low!.operator === comp) &&
             ~~~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1751:14

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
      (!low!.operator || low!.operator === comp) &&
                              ~~~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1751:31

TS2339 [ERROR]: Property 'semver' does not exist on type 'never'.
      ltefn(version, low!.semver)
                          ~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1752:27

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    } else if (low!.operator === ecomp && ltfn(version, low!.semver)) {
                    ~~~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1755:21

TS2339 [ERROR]: Property 'semver' does not exist on type 'never'.
    } else if (low!.operator === ecomp && ltfn(version, low!.semver)) {
                                                             ~~~~~~
    at https://deno.land/x/semver@v1.0.0/mod.ts:1755:62

Found 7 errors.
```

**Comment by oscarotero** [comment]
Hi, @prathithacb 
Yes, you have to update changelog to v1.1.1.
Let me know if you find any issue!

**Comment by shah** [comment]
@oscarotero it seems that version v1.1.1 is in the "releases" tag. I use `curl -s https://api.github.com/repos/{{repo}}/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`  command to find the latest release tag and pull that one in to make sure we're getting the right release. Would you mind running your CI scripts to generate a release?

Thanks!

**Comment by oscarotero** [comment]
Yes, it was not as a release, but a tag (https://github.com/oscarotero/keep-a-changelog/releases/tag/v1.1.1) I just created a release.

It's also available in deno.land/x https://deno.land/x/changelog@v1.1.1

**Comment by shah** [comment]
Fantastic, thanks @oscarotero!
